kind: Deployment
apiVersion: apps/v1
metadata:
  name: quarkus-dynatrace-app
  labels:
    app: quarkus-dynatrace-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-dynatrace-app
  template:
    metadata:
      labels:
        app: quarkus-dynatrace-app
    spec:
      containers:
        - name: quarkus-dynatrace-app
          image: matheuscruzdev/quarkus-dynatrace:latest
          ports:
              - containerPort: 8080
                protocol: TCP
          env:
            - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://dynatrace-otel-collector.default.svc.cluster.local:4317"
            - name: QUARKUS_OTEL_METRICS_ENABLED
              value: "true"
            - name: QUARKUS_OTEL_EXPORTER_OTLP_ENABLED
              value: "true"
            - name: QUARKUS_OTEL_LOGS_ENABLED
              value: "true"
            - name: QUARKUS_LOG_LEVEL
              value: "INFO"
            - name: QUARKUS_OTEL_TRACES_ENABLED
              value: "true"
---
kind: Service
apiVersion: v1
metadata:
  name: quarkus-dynatrace-app
  labels:
    app: quarkus-dynatrace-app
spec:
  selector:
    app: quarkus-dynatrace-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---